//! Golden tests for per-language reference extractors: what gets extracted,
//! how qualified calls split, scope attribution, builtin filtering,
//! and test-file detection.

use code_abyss::graph::languages::get_extractor;
use code_abyss::graph::{RawReference, RefKind};
use code_abyss::indexer::parser::MultiParser;

fn extract(lang: &str, source: &str) -> Vec<RawReference> {
    let parser = MultiParser::new();
    let tree = parser.parse(source, lang).unwrap();
    get_extractor(lang).unwrap().extract(&tree, source)
}

// --- Generated-code detection ---

#[test]
fn detects_generated_markers() {
    use code_abyss::indexer::parser::is_generated;
    // Go convention (ent, protoc-gen-go, mockgen, stringer, sqlc)
    assert!(is_generated(
        "// Code generated by ent, DO NOT EDIT.\n\npackage ent\n"
    ));
    assert!(is_generated(
        "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n"
    ));
    // Meta convention
    assert!(is_generated(
        "/**\n * @generated\n */\nexport const x = 1;\n"
    ));
    // protobuf python
    assert!(is_generated(
        "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
    ));
    // .NET
    assert!(is_generated("// <auto-generated>\nnamespace Foo {}\n"));
    // marker after a license header still caught (within head window)
    assert!(is_generated(
        "// Copyright 2026\n// Licensed under MIT\n\n// Code generated by tool. DO NOT EDIT.\npackage x\n"
    ));
}

#[test]
fn hand_written_code_is_not_generated() {
    use code_abyss::indexer::parser::is_generated;
    assert!(!is_generated(
        "package app\n\nfunc Real() int { return 1 }\n"
    ));
    // a passing mention deep in the file (beyond the head window) doesn't trip it
    let mut deep = String::from("package app\n");
    for i in 0..60 {
        deep.push_str(&format!("// line {i}\n"));
    }
    deep.push_str("// DO NOT EDIT this constant below\n");
    assert!(!is_generated(&deep));
}

fn find<'a>(refs: &'a [RawReference], name: &str, kind: RefKind) -> Option<&'a RawReference> {
    refs.iter()
        .find(|r| r.target_name == name && r.kind == kind)
}

// --- Go ---

#[test]
fn go_direct_and_qualified_calls() {
    let refs = extract(
        "go",
        r#"package app

import "example.com/proj/util"

func Caller() int {
	x := Local()
	return util.Remote(x)
}
"#,
    );
    let local = find(&refs, "Local", RefKind::Call).expect("Local call");
    assert_eq!(local.target_qualifier, None);
    assert_eq!(local.source_symbol.as_deref(), Some("Caller"));

    let remote = find(&refs, "Remote", RefKind::Call).expect("Remote call");
    assert_eq!(remote.target_qualifier.as_deref(), Some("util"));

    let import = find(&refs, "example.com/proj/util", RefKind::Import).expect("import");
    assert_eq!(import.source_symbol, None);
}

#[test]
fn go_type_refs_and_builtin_filtering() {
    let refs = extract(
        "go",
        r#"package app

func Build(a Account) int {
	items := make([]int, 0)
	return len(items)
}
"#,
    );
    assert!(find(&refs, "Account", RefKind::TypeRef).is_some());
    assert!(
        find(&refs, "make", RefKind::Call).is_none(),
        "builtin make filtered"
    );
    assert!(
        find(&refs, "len", RefKind::Call).is_none(),
        "builtin len filtered"
    );
}

#[test]
fn go_test_file_detection() {
    let ex = get_extractor("go").unwrap();
    assert!(ex.is_test_file("pkg/handler_test.go"));
    assert!(!ex.is_test_file("pkg/handler.go"));
}

// --- Rust ---

#[test]
fn rust_path_call_splits_qualifier() {
    let refs = extract(
        "rust",
        "fn run() {\n    let x = crate::storage::open();\n    helper();\n}\n",
    );
    let open = find(&refs, "open", RefKind::Call).expect("path call");
    assert_eq!(open.target_qualifier.as_deref(), Some("crate::storage"));
    assert_eq!(open.source_symbol.as_deref(), Some("run"));

    let helper = find(&refs, "helper", RefKind::Call).expect("direct call");
    assert_eq!(helper.target_qualifier, None);
}

#[test]
fn rust_method_call_splits_receiver() {
    let refs = extract("rust", "fn run(repo: Repo) {\n    repo.commit();\n}\n");
    let commit = find(&refs, "commit", RefKind::Call).expect("method call split on '.'");
    assert_eq!(commit.target_qualifier.as_deref(), Some("repo"));
}

#[test]
fn rust_use_decl_and_builtin_filtering() {
    let refs = extract(
        "rust",
        "use crate::storage::Repository;\n\nfn run() -> Option<u32> {\n    Some(1)\n}\n",
    );
    assert!(find(&refs, "crate::storage::Repository", RefKind::Import).is_some());
    assert!(
        find(&refs, "Some", RefKind::Call).is_none(),
        "Some filtered"
    );
}

// --- Python ---

#[test]
fn python_attribute_call_and_imports() {
    let refs = extract(
        "python",
        "import util\nfrom pkg.mod import thing\n\ndef caller():\n    util.pfn()\n    local()\n",
    );
    let pfn = find(&refs, "pfn", RefKind::Call).expect("attribute call");
    assert_eq!(pfn.target_qualifier.as_deref(), Some("util"));
    assert_eq!(pfn.source_symbol.as_deref(), Some("caller"));

    assert!(find(&refs, "local", RefKind::Call).is_some());
    assert!(find(&refs, "util", RefKind::Import).is_some());
    assert!(find(&refs, "pkg.mod", RefKind::Import).is_some());
}

#[test]
fn python_builtin_filtering() {
    let refs = extract("python", "def f(xs):\n    print(len(xs))\n");
    assert!(find(&refs, "print", RefKind::Call).is_none());
    assert!(find(&refs, "len", RefKind::Call).is_none());
}

#[test]
fn python_test_file_detection() {
    let ex = get_extractor("python").unwrap();
    assert!(ex.is_test_file("pkg/test_handler.py"));
    assert!(ex.is_test_file("proj/tests/anything.py"));
    assert!(!ex.is_test_file("pkg/handler.py"));
}

#[test]
fn python_class_inheritance_refs() {
    let refs = extract(
        "python",
        "import click\n\nclass Base:\n    pass\n\nclass Mid(Base):\n    pass\n\nclass Leaf(Mid, OtherBase, metaclass=Meta):\n    pass\n\nclass Q(click.Command):\n    pass\n",
    );

    let base_inh = find(&refs, "Base", RefKind::Inherit).expect("Mid -> Base");
    assert_eq!(base_inh.source_symbol.as_deref(), Some("Mid"));
    assert!(base_inh.target_qualifier.is_none());

    // Multi-base: both Mid and OtherBase emitted, metaclass kwarg skipped.
    let mid_inh = find(&refs, "Mid", RefKind::Inherit).expect("Leaf -> Mid");
    assert_eq!(mid_inh.source_symbol.as_deref(), Some("Leaf"));
    assert!(find(&refs, "OtherBase", RefKind::Inherit).is_some());
    assert!(
        find(&refs, "Meta", RefKind::Inherit).is_none(),
        "metaclass kwarg must not become an inherits ref"
    );

    // Qualified base: target_name is the type, qualifier is the module.
    let qual_inh = find(&refs, "Command", RefKind::Inherit).expect("Q -> click.Command");
    assert_eq!(qual_inh.target_qualifier.as_deref(), Some("click"));
    assert_eq!(qual_inh.source_symbol.as_deref(), Some("Q"));
}

// --- TypeScript / JavaScript ---

#[test]
fn ts_member_call_new_and_import() {
    let refs = extract(
        "typescript",
        "import { api } from './api';\n\nfunction caller(): Widget {\n  api.fetchUser();\n  build();\n  return new Widget();\n}\n",
    );
    let fetch = find(&refs, "fetchUser", RefKind::Call).expect("member call");
    assert_eq!(fetch.target_qualifier.as_deref(), Some("api"));
    assert_eq!(fetch.source_symbol.as_deref(), Some("caller"));

    assert!(find(&refs, "build", RefKind::Call).is_some());
    assert!(
        find(&refs, "Widget", RefKind::Call).is_some(),
        "new expression"
    );
    assert!(find(&refs, "./api", RefKind::Import).is_some());
    assert!(find(&refs, "Widget", RefKind::TypeRef).is_some());
}

#[test]
fn ts_builtin_filtering_and_test_detection() {
    let refs = extract(
        "typescript",
        "function f(x: string): number {\n  return parseInt(x);\n}\n",
    );
    assert!(find(&refs, "parseInt", RefKind::Call).is_none());
    assert!(find(&refs, "string", RefKind::TypeRef).is_none());

    let ex = get_extractor("typescript").unwrap();
    assert!(ex.is_test_file("src/api.test.ts"));
    assert!(ex.is_test_file("src/__tests__/api.ts"));
    assert!(!ex.is_test_file("src/api.ts"));
}

#[test]
fn javascript_uses_same_extractor() {
    let refs = extract("javascript", "function f() {\n  helper();\n}\n");
    assert!(find(&refs, "helper", RefKind::Call).is_some());
}

#[test]
fn tsx_jsx_component_and_attribute_expression_extracted() {
    // v0.5.1 hono dogfood (L3): .tsx files had higher unresolved-ref rate
    // because the visitor never fired on JSX-specific nodes. Component
    // names in opening elements and identifiers in JSX expression
    // attributes were dropped on the floor.
    //
    // Pin: `<Foo bar={someValue} />` MUST extract refs for both `Foo`
    // and `someValue` so L0b can resolve them via import binding.
    let refs = extract(
        "tsx",
        "import { Foo, someValue } from './m';\n\
         export function App() {\n  \
           return <Foo bar={someValue} />;\n\
         }\n",
    );
    let foo = find(&refs, "Foo", RefKind::Call).expect("JSX component name");
    assert_eq!(foo.source_symbol.as_deref(), Some("App"));
    let some = find(&refs, "someValue", RefKind::Call).expect("JSX attribute identifier");
    assert_eq!(some.source_symbol.as_deref(), Some("App"));
    // Sanity: the named-import binding edges should be in the raw refs too,
    // so the resolver pipeline has the L0b evidence it needs.
    assert!(
        refs.iter()
            .any(|r| r.kind == RefKind::ImportBinding && r.target_name == "Foo"),
        "expected ImportBinding(Foo) → './m', got: {:?}",
        refs.iter()
            .map(|r| (&r.kind, &r.target_name))
            .collect::<Vec<_>>(),
    );
}

#[test]
fn tsx_lowercase_intrinsics_do_not_pollute_call_graph() {
    // HTML intrinsics like <div>, <span>, <main> are not user-defined
    // components — they must NOT become unresolvable Call refs polluting
    // the graph. JSX convention: Pascal-case component, lowercase
    // intrinsic.
    let refs = extract(
        "tsx",
        "export function App() {\n  return <div className=\"x\"><span /></div>;\n}\n",
    );
    assert!(
        find(&refs, "div", RefKind::Call).is_none(),
        "intrinsic <div> must not surface as a Call ref"
    );
    assert!(
        find(&refs, "span", RefKind::Call).is_none(),
        "intrinsic <span> must not surface as a Call ref"
    );
}

#[test]
fn tsx_nested_member_component_extracts_rightmost_name() {
    // `<Comp.SubItem />` — extract `SubItem` with qualifier `Comp`. Matches
    // how member-expression calls are extracted at the function position.
    let refs = extract(
        "tsx",
        "import { Comp } from './m';\n\
         export function App() {\n  return <Comp.SubItem />;\n}\n",
    );
    let sub = refs
        .iter()
        .find(|r| r.target_name == "SubItem" && r.kind == RefKind::Call)
        .expect("nested member component");
    assert_eq!(sub.target_qualifier.as_deref(), Some("Comp"));
}

// --- Java ---

#[test]
fn java_method_calls_and_constructor() {
    let refs = extract(
        "java",
        r#"package app;

import com.example.util.Helper;

public class Service {
    public int run() {
        Helper h = new Helper();
        int x = h.compute(1);
        return local(x);
    }

    private int local(int x) { return x; }
}
"#,
    );
    let compute = find(&refs, "compute", RefKind::Call).expect("method call");
    assert_eq!(compute.target_qualifier.as_deref(), Some("h"));
    assert_eq!(compute.source_symbol.as_deref(), Some("run"));

    let ctor = find(&refs, "Helper", RefKind::Call).expect("constructor call");
    assert_eq!(ctor.target_qualifier, None);

    assert!(find(&refs, "local", RefKind::Call).is_some());
    assert!(find(&refs, "com.example.util.Helper", RefKind::Import).is_some());
    assert!(find(&refs, "Helper", RefKind::TypeRef).is_some());
}

#[test]
fn java_builtin_filtering_and_generics() {
    let refs = extract(
        "java",
        "import java.util.List;\n\npublic class A {\n    java.util.List<String> f() {\n        return new java.util.ArrayList<String>();\n    }\n}\n",
    );
    assert!(
        find(&refs, "ArrayList", RefKind::Call).is_none(),
        "builtin ctor filtered"
    );
    assert!(
        find(&refs, "String", RefKind::TypeRef).is_none(),
        "builtin type filtered"
    );
}

#[test]
fn java_test_file_detection() {
    let ex = get_extractor("java").unwrap();
    assert!(ex.is_test_file("src/test/java/app/ServiceTest.java"));
    assert!(ex.is_test_file("app/ServiceTest.java"));
    assert!(!ex.is_test_file("src/main/java/app/Service.java"));
}

// --- C ---

#[test]
fn c_direct_and_qualified_calls() {
    let refs = extract(
        "c",
        r#"
#include "myutil.h"

void helper(int n);

int caller(int x) {
    helper(x);
    return custom_fn(x);
}
"#,
    );
    let helper = find(&refs, "helper", RefKind::Call).expect("direct call");
    assert_eq!(helper.target_qualifier, None);
    assert_eq!(helper.source_symbol.as_deref(), Some("caller"));

    assert!(find(&refs, "custom_fn", RefKind::Call).is_some());
    assert!(find(&refs, "myutil.h", RefKind::Import).is_some());
}

#[test]
fn c_member_access_via_dot_and_arrow() {
    let refs = extract(
        "c",
        r#"
void process(struct Ctx* ctx) {
    ctx->run(1);
    struct Obj o;
    o.update();
}
"#,
    );
    let run = find(&refs, "run", RefKind::Call).expect("arrow call");
    assert_eq!(run.target_qualifier.as_deref(), Some("ctx"));
    assert_eq!(run.receiver_type.as_deref(), Some("Ctx"));

    let update = find(&refs, "update", RefKind::Call).expect("dot call");
    assert_eq!(update.target_qualifier.as_deref(), Some("o"));
    assert_eq!(update.receiver_type.as_deref(), Some("Obj"));
}

#[test]
fn c_type_refs_and_builtin_filtering() {
    let refs = extract(
        "c",
        r#"
Point make_point(int x) {
    printf("hi");
    Point* p = malloc(sizeof(Point));
    return *p;
}
"#,
    );
    assert!(
        find(&refs, "Point", RefKind::TypeRef).is_some(),
        "custom type ref"
    );
    assert!(
        find(&refs, "printf", RefKind::Call).is_none(),
        "builtin printf filtered"
    );
    assert!(
        find(&refs, "malloc", RefKind::Call).is_none(),
        "builtin malloc filtered"
    );
}

#[test]
fn c_system_include_not_captured() {
    let refs = extract(
        "c",
        r#"
#include <stdio.h>
#include "local.h"

void f() {}
"#,
    );
    assert!(
        find(&refs, "local.h", RefKind::Import).is_some(),
        "local include captured"
    );
    // system includes should NOT be captured
    assert!(
        refs.iter()
            .all(|r| r.target_name != "stdio.h" || r.kind != RefKind::Import),
        "system include not captured"
    );
}

#[test]
fn c_test_file_detection() {
    let ex = get_extractor("c").unwrap();
    assert!(ex.is_test_file("src/parser_test.c"));
    assert!(ex.is_test_file("tests/test_parser.c"));
    assert!(!ex.is_test_file("src/parser.c"));
}

// --- C++ ---

#[test]
fn cpp_method_call_and_new_expression() {
    let refs = extract(
        "cpp",
        r#"
#include "engine.h"

void caller() {
    Engine* e = new Engine();
    e->start(1);
    helper();
}
"#,
    );
    let start = find(&refs, "start", RefKind::Call).expect("arrow method call");
    assert_eq!(start.target_qualifier.as_deref(), Some("e"));
    assert_eq!(start.receiver_type.as_deref(), Some("Engine"));

    assert!(
        find(&refs, "Engine", RefKind::Call).is_some(),
        "new expression → constructor call"
    );
    assert!(find(&refs, "helper", RefKind::Call).is_some());
    assert!(find(&refs, "engine.h", RefKind::Import).is_some());
}

#[test]
fn cpp_qualified_call_filters_std() {
    let refs = extract(
        "cpp",
        r#"
void f() {
    std::sort(v.begin(), v.end());
    game::Engine::create();
}
"#,
    );
    assert!(
        find(&refs, "sort", RefKind::Call).is_none(),
        "std:: calls filtered"
    );
    let create = find(&refs, "create", RefKind::Call).expect("qualified call");
    assert_eq!(create.target_qualifier.as_deref(), Some("game::Engine"));
}

#[test]
fn cpp_class_method_this_receiver() {
    let refs = extract(
        "cpp",
        r#"
class Player {
public:
    void move(int dx) {
        this->update(dx);
        helper();
    }
};
"#,
    );
    let update = find(&refs, "update", RefKind::Call).expect("this->method");
    assert_eq!(update.receiver_type.as_deref(), Some("Player"));
}

#[test]
fn cpp_inheritance_ref() {
    let refs = extract(
        "cpp",
        r#"
class Animal {
public:
    virtual void speak();
};

class Dog : public Animal {
public:
    void speak() override {}
};
"#,
    );
    assert!(
        find(&refs, "Animal", RefKind::Inherit).is_some(),
        "inheritance ref"
    );
}

#[test]
fn cpp_builtin_type_filtering() {
    let refs = extract(
        "cpp",
        r#"
Widget create(int x, bool flag) {
    string name;
    return Widget();
}
"#,
    );
    assert!(find(&refs, "Widget", RefKind::TypeRef).is_some());
    assert!(
        find(&refs, "string", RefKind::TypeRef).is_none(),
        "builtin string filtered"
    );
    assert!(
        find(&refs, "bool", RefKind::TypeRef).is_none(),
        "builtin bool filtered"
    );
}

#[test]
fn cpp_test_file_detection() {
    let ex = get_extractor("cpp").unwrap();
    assert!(ex.is_test_file("src/engine_test.cpp"));
    assert!(ex.is_test_file("tests/TestEngine.cc"));
    assert!(ex.is_test_file("testing/foo.cpp"));
    assert!(!ex.is_test_file("src/engine.cpp"));
}
