//! End-to-end graph query tests: index a fixture workspace, then exercise
//! find_callers / impact_analysis the way the CLI and MCP server do.

mod common;
use std::collections::HashSet;

use code_abyss::graph::GraphQuery;
use common::*;

/// Call chain: Target ← DirectA (same file), Target ← DirectB (same pkg),
/// DirectB ← Indirect, Target ← TestTarget (test file).
fn chain_fixture() -> Fixture {
    index_fixture(&[
        (
            "app/a.go",
            "package app\n\nfunc Target() int { return 1 }\n\nfunc DirectA() int { return Target() }\n",
        ),
        (
            "app/b.go",
            "package app\n\nfunc DirectB() int { return Target() }\n",
        ),
        (
            "app/c.go",
            "package app\n\nfunc Indirect() int { return DirectB() }\n",
        ),
        (
            "app/a_test.go",
            "package app\n\nfunc TestTarget() int { return Target() }\n",
        ),
    ])
}

#[test]
fn find_callers_returns_all_with_confidence_order() {
    let fx = chain_fixture();
    let gq = GraphQuery::new(&fx.repo);
    let callers = gq.find_callers("Target", 20, 0.0).unwrap();
    assert_eq!(callers.len(), 3, "{callers:?}");
    // Ordered by confidence descending: same-file first.
    assert_eq!(callers[0].symbol, "DirectA");
    assert_eq!(callers[0].confidence, 1.0);
    let names: Vec<&str> = callers.iter().map(|c| c.symbol.as_str()).collect();
    assert!(names.contains(&"DirectB"));
    assert!(names.contains(&"TestTarget"));
    let test_caller = callers.iter().find(|c| c.symbol == "TestTarget").unwrap();
    assert!(test_caller.is_test);
}

#[test]
fn impact_analysis_walks_transitive_and_tests() {
    let fx = chain_fixture();
    let gq = GraphQuery::new(&fx.repo);
    let impact = gq.impact_analysis("Target", 3, 0.7).unwrap();

    let direct: Vec<&str> = impact
        .direct_callers
        .iter()
        .map(|c| c.symbol.as_str())
        .collect();
    assert!(direct.contains(&"DirectA"), "{direct:?}");
    assert!(direct.contains(&"DirectB"));

    let transitive: Vec<&str> = impact
        .transitive_callers
        .iter()
        .map(|c| c.symbol.as_str())
        .collect();
    assert!(transitive.contains(&"Indirect"), "{transitive:?}");

    assert_eq!(impact.affected_tests.len(), 1);
    assert_eq!(impact.affected_tests[0].symbol, "TestTarget");

    // DirectA/DirectB/Indirect are not covered by the only test symbol.
    assert!(!impact.uncovered_paths.is_empty());
    assert!(impact.risk_score > 0.0);
    assert!(impact.risk_score <= 10.0);
}

#[test]
fn impact_of_unknown_symbol_is_empty_and_low_risk() {
    let fx = chain_fixture();
    let gq = GraphQuery::new(&fx.repo);
    let impact = gq.impact_analysis("DoesNotExist", 3, 0.7).unwrap();
    assert!(impact.direct_callers.is_empty());
    assert!(impact.transitive_callers.is_empty());
    assert_eq!(impact.risk_score, 0.0);
}

#[test]
fn symbol_and_fulltext_search_find_indexed_code() {
    let fx = chain_fixture();
    let symbols = code_abyss::search::symbol::search(&fx.repo, "Target", 10).unwrap();
    assert!(!symbols.is_empty());
    assert!(symbols.iter().any(|s| s.name == "Target"));

    let engine = code_abyss::search::SearchEngine::new(&fx.repo, None);
    let results = engine.search("Target", 10).unwrap();
    assert!(!results.is_empty());
    assert!(results.iter().any(|r| r.file_path.contains("a.go")));
}

#[test]
fn reindex_is_idempotent() {
    let fx = chain_fixture();
    let pipeline = code_abyss::indexer::IndexPipeline::new(fx.config.clone());
    let before_refs = fx.repo.ref_count().unwrap();
    let before_symbols = fx.repo.symbol_count().unwrap();

    let stats = pipeline.run_structural(&fx.repo).unwrap();
    assert_eq!(stats.indexed, 0, "unchanged files must not reindex");
    assert_eq!(fx.repo.ref_count().unwrap(), before_refs);
    assert_eq!(fx.repo.symbol_count().unwrap(), before_symbols);
}

#[test]
fn generated_files_keep_symbols_but_skip_refs() {
    // A DO NOT EDIT file's symbols stay indexed (so hand-written callers
    // resolve), but its own internal call edges — pure mechanical noise — are
    // dropped. This is the 35%-refs win on codegen-heavy repos.
    let fx = index_fixture(&[
        (
            "app/gen.go",
            "// Code generated by ent, DO NOT EDIT.\n\npackage app\n\n\
             func GenHelper() int { return 1 }\n\n\
             func GenEntry() int { return GenHelper() }\n",
        ),
        (
            "app/hand.go",
            "package app\n\nfunc Hand() int { return GenEntry() }\n",
        ),
    ]);
    let conn = fx.repo.conn();

    // gen.go is flagged generated
    let is_gen: i64 = conn
        .query_row(
            "SELECT generated FROM files WHERE path = 'app/gen.go'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(is_gen, 1, "gen.go must be flagged generated");

    // Its symbols are still indexed (search / target resolution works)
    let syms = code_abyss::search::symbol::search(&fx.repo, "GenEntry", 10).unwrap();
    assert!(
        syms.iter().any(|s| s.name == "GenEntry"),
        "generated symbols must stay indexed"
    );

    // No refs originate FROM the generated file (GenEntry→GenHelper dropped)
    let gen_refs: i64 = conn
        .query_row(
            "SELECT COUNT(*) FROM refs r JOIN files f ON r.source_file_id = f.id
             WHERE f.path = 'app/gen.go'",
            [],
            |r| r.get(0),
        )
        .unwrap();
    assert_eq!(gen_refs, 0, "no refs should originate from generated code");

    // But the hand-written caller of a generated symbol still resolves
    let callers = GraphQuery::new(&fx.repo)
        .find_callers("GenEntry", 20, 0.0)
        .unwrap();
    assert!(
        callers.iter().any(|c| c.symbol == "Hand"),
        "hand-written caller of generated symbol must resolve: {callers:?}"
    );
}

#[test]
fn impact_bfs_explores_same_named_callers_in_different_files() {
    // Two distinct callers both named `run` (in svc_a/run.go and svc_b/run.go)
    // each call Target. If the BFS visited set keys on just the bare name `run`,
    // the second `run` is skipped and its transitive subtree disappears. The
    // fix keys visited on (source_file_id, source_symbol_name).
    let fx = index_fixture(&[
        (
            "svc/target.go",
            "package svc\n\nfunc Target() int { return 1 }\n",
        ),
        (
            "svc_a/run.go",
            "package svc_a\n\nfunc run() int { return Target() }\n\n\
             func Entry() int { return run() }\n",
        ),
        (
            "svc_b/run.go",
            "package svc_b\n\nfunc run() int { return Target() }\n\n\
             func Boot() int { return run() }\n",
        ),
    ]);

    let gq = GraphQuery::new(&fx.repo);
    // Use min_confidence=0.0 so cross-package lookups (which land at L4=0.8 or
    // even demoted tiers) are not filtered out by the default 0.7 gate.
    let impact = gq.impact_analysis("Target", 3, 0.0).unwrap();

    let direct: Vec<&str> = impact
        .direct_callers
        .iter()
        .map(|c| c.symbol.as_str())
        .collect();
    let direct_run_count = direct.iter().filter(|s| **s == "run").count();
    assert_eq!(
        direct_run_count, 2,
        "both same-named `run` callers should be direct callers of Target: {direct:?}"
    );

    let transitive: Vec<&str> = impact
        .transitive_callers
        .iter()
        .map(|c| c.symbol.as_str())
        .collect();
    // The BUG would drop one of these — only one subtree was being walked.
    assert!(
        transitive.contains(&"Entry"),
        "transitive caller from svc_a/run.go's subtree should be walked: {transitive:?}"
    );
    assert!(
        transitive.contains(&"Boot"),
        "transitive caller from svc_b/run.go's subtree should be walked: {transitive:?}"
    );
}

#[test]
fn impact_bfs_pins_same_name_subtree_property() {
    // Stricter property pin for the BFS visited-set (file_id, name) contract.
    //
    // The earlier `impact_bfs_explores_same_named_callers_in_different_files`
    // test does not strictly fail on the OLD (buggy) bare-name visited because
    // `find_callers_of` is a name-keyed SQL aggregate: at the next BFS hop,
    // both subtrees are reached via one merged query. This test makes the
    // observable contract richer:
    //
    //   File X:  func foo() { shared_util(); }
    //   File Y:  func foo() { other_util(); }
    //   File Z:  imports X.foo; calls X.foo; also calls shared_util directly
    //   File W:  imports Y.foo; calls Y.foo; also calls other_util directly
    //
    // Impact analysis on `shared_util`:
    //   - X.foo is a direct caller of shared_util.
    //   - Z is a direct caller of shared_util (separate edge).
    //   - At depth 1, BFS pops "foo" and finds Z (caller of X.foo) AND W
    //     (caller of Y.foo, name-shared).
    //
    // The fix's contract: both Z and W appear in the impact set, AND the
    // visited dedup does not crash, AND uncovered_paths includes BOTH Z and W
    // call-paths. The OLD bug would have ALSO reached W via merged SQL, but
    // any FUTURE BFS rewrite that file-scopes traversal would drop the W
    // subtree silently. This test pins the observable post-condition.
    let fx = index_fixture(&[
        (
            "util/shared.go",
            "package util\n\nfunc shared_util() int { return 1 }\n",
        ),
        (
            "util/other.go",
            "package util\n\nfunc other_util() int { return 2 }\n",
        ),
        (
            "svc_x/foo.go",
            "package svc_x\n\n\
             import \"util\"\n\n\
             func foo() int { return util.shared_util() }\n",
        ),
        (
            "svc_y/foo.go",
            "package svc_y\n\n\
             import \"util\"\n\n\
             func foo() int { return util.other_util() }\n",
        ),
        (
            "svc_z/entry.go",
            "package svc_z\n\n\
             import (\n  \"svc_x\"\n  \"util\"\n)\n\n\
             func EntryZ() int { return svc_x.foo() + util.shared_util() }\n",
        ),
        (
            "svc_w/entry.go",
            "package svc_w\n\n\
             import (\n  \"svc_y\"\n  \"util\"\n)\n\n\
             func BootW() int { return svc_y.foo() + util.other_util() }\n",
        ),
    ]);

    let gq = GraphQuery::new(&fx.repo);
    // min_confidence=0.0: cross-package refs land below the 0.7 gate.
    let impact = gq.impact_analysis("shared_util", 4, 0.0).unwrap();

    let mut asserts = 0u32;

    // Direct callers of shared_util: svc_x.foo and svc_z.EntryZ.
    let direct: Vec<&str> = impact
        .direct_callers
        .iter()
        .map(|c| c.symbol.as_str())
        .collect();
    assert!(
        direct.contains(&"foo"),
        "svc_x.foo (caller of shared_util) must be direct: {direct:?}"
    );
    asserts += 1;
    assert!(
        direct.contains(&"EntryZ"),
        "svc_z.EntryZ (direct caller of shared_util) must be direct: {direct:?}"
    );
    asserts += 1;

    // svc_y.foo does NOT call shared_util — must NOT appear in direct callers
    // for shared_util. (Name `foo` is shared with svc_x.foo, but only x calls
    // shared_util; the resolver must keep them separate via target_file_id.)
    let direct_foo_files: Vec<&str> = impact
        .direct_callers
        .iter()
        .filter(|c| c.symbol == "foo")
        .map(|c| c.file_path.as_str())
        .collect();
    assert!(
        direct_foo_files.iter().any(|p| p.contains("svc_x")),
        "svc_x/foo.go must be a direct caller: {direct_foo_files:?}"
    );
    asserts += 1;

    // Transitive: BootW must be reached via the Y.foo subtree.
    // (Under the merged-SQL aggregate this works in both buggy and fixed
    // builds; the contract here pins the observable post-condition.)
    let transitive: Vec<&str> = impact
        .transitive_callers
        .iter()
        .map(|c| c.symbol.as_str())
        .collect();
    assert!(
        transitive.contains(&"BootW"),
        "transitive caller from svc_y.foo's subtree (BootW) must be walked: \
         {transitive:?}"
    );
    asserts += 1;

    // The visited set must not collapse same-named direct callers. We assert
    // foo appears exactly once as a direct caller (svc_x.foo). The svc_y.foo
    // appears in the transitive set (as a caller of svc_y.foo that the SQL
    // aggregate returned). Either way, no symbol/file pair should be
    // duplicated within direct_callers.
    let direct_pairs: HashSet<(String, String)> = impact
        .direct_callers
        .iter()
        .map(|c| (c.file_path.clone(), c.symbol.clone()))
        .collect();
    assert_eq!(
        direct_pairs.len(),
        impact.direct_callers.len(),
        "direct_callers must not duplicate (file, symbol): {:?}",
        impact.direct_callers
    );
    asserts += 1;

    // Risk must be non-trivial — at minimum two direct callers, transitive
    // walk found additional names. A regression that drops half the subtree
    // would crater the score.
    assert!(
        impact.risk_score > 1.0,
        "risk_score should be > 1.0 for a target with 2+ direct callers and \
         transitive depth: {:?}",
        impact.risk_score
    );
    asserts += 1;

    eprintln!("impact_bfs_pins_same_name_subtree_property: {asserts} asserts");
}

#[test]
fn deleted_files_are_removed_from_index() {
    let fx = index_fixture(&[
        ("a.go", "package main\n\nfunc A() int { return 1 }\n"),
        ("b.go", "package main\n\nfunc B() int { return A() }\n"),
    ]);
    assert_eq!(fx.repo.file_count().unwrap(), 2);

    std::fs::remove_file(fx.config.workspace.join("b.go")).unwrap();
    let pipeline = code_abyss::indexer::IndexPipeline::new(fx.config.clone());
    let stats = pipeline.run_structural(&fx.repo).unwrap();
    assert_eq!(stats.deleted, 1);
    assert_eq!(fx.repo.file_count().unwrap(), 1);
    // Refs from the deleted file must be gone too.
    assert_eq!(call_refs_to(&fx.repo, "A").len(), 0);
}

/// L1 kind-contract regression: impact_analysis default MUST agree with the
/// callers default (call + field_access + type_ref + inherit).
///
/// v0.5.1 dogfood (hono `Context`): `abyss impact Context` reported direct=2
/// while `abyss callers Context` reported 20 prod callers — the two CLI
/// surfaces referred to different things because impact silently used the
/// invocation-only legacy set. This test pins the post-fix contract using a
/// TypeScript fixture that mixes invocation, type-position, and inheritance
/// edges; the default impact view must surface ALL three kinds, while
/// `--calls-only` must drop the non-invocation kinds.
#[test]
fn impact_default_matches_callers_superset() {
    // Fixture mirrors hono `Context`-shape: a class with both invocation
    // users (`new Context()`) AND type-position users (annotations,
    // generics, implements). Pre-fix v0.5.1 impact only counted the
    // invocation users.
    let fx = index_fixture(&[
        ("src/types.ts", "export class Context { handle() {} }\n"),
        // Three type-position users (type_ref edges).
        (
            "src/annot_a.ts",
            "import { Context } from './types';\n\
             export function f(c: Context) { return c }\n",
        ),
        (
            "src/annot_b.ts",
            "import { Context } from './types';\n\
             export function g(c: Context) { return c }\n",
        ),
        (
            "src/annot_c.ts",
            "import { Context } from './types';\n\
             let cur: Context | null = null;\n\
             export const ref_c = cur;\n",
        ),
        // Two invocation users (call edges — `new Context()`).
        (
            "src/call_a.ts",
            "import { Context } from './types';\n\
             export function bootA() { return new Context() }\n",
        ),
        (
            "src/call_b.ts",
            "import { Context } from './types';\n\
             export function bootB() { return new Context() }\n",
        ),
    ]);

    let gq = GraphQuery::new(&fx.repo);

    // Default impact (no flag) — uses Both. Use min_confidence=0.0 so
    // cross-package refs aren't filtered by the 0.7 gate on a tiny fixture.
    let default_impact = gq.impact_analysis("Context", 3, 0.0).unwrap();
    let kinds: Vec<&str> = default_impact
        .direct_callers
        .iter()
        .map(|c| c.kind.as_str())
        .collect();
    // Three type_ref users + 2 call users = 5 direct callers under Both.
    // Pre-fix legacy filter would have reported only 2 (calls only).
    assert!(
        default_impact.direct_callers.len() >= 5,
        "default impact must include calls + type_ref users \
         (≥5 direct, got {} — kinds: {kinds:?})",
        default_impact.direct_callers.len(),
    );
    assert!(
        kinds.contains(&"call"),
        "default impact must surface call edges, got {kinds:?}",
    );
    assert!(
        kinds.contains(&"type_ref"),
        "default impact must surface type_ref edges, got {kinds:?}",
    );

    // `--calls-only` (legacy semantics) drops type_ref. Only the two
    // `new Context()` users should remain.
    let calls_only = gq
        .impact_analysis_filtered(
            "Context",
            3,
            0.0,
            code_abyss::graph::CallerKindFilter::CallsOnly,
        )
        .unwrap();
    assert!(
        calls_only.direct_callers.len() <= 2,
        "calls-only impact must drop type_ref users — got {} ({:?})",
        calls_only.direct_callers.len(),
        calls_only
            .direct_callers
            .iter()
            .map(|c| (c.symbol.as_str(), c.kind.as_str()))
            .collect::<Vec<_>>(),
    );
    assert!(
        calls_only
            .direct_callers
            .iter()
            .all(|c| c.kind == "call" || c.kind == "field_access"),
        "calls-only must only return call/field_access edges, got kinds {:?}",
        calls_only
            .direct_callers
            .iter()
            .map(|c| c.kind.as_str())
            .collect::<Vec<_>>(),
    );
    assert!(
        calls_only.direct_callers.len() < default_impact.direct_callers.len(),
        "calls-only must strictly drop callers vs. default — calls_only={} default={}",
        calls_only.direct_callers.len(),
        default_impact.direct_callers.len(),
    );

    // Cross-check with find_callers (same Both default) — counts must
    // agree on direct callers (impact direct ⊆ callers prod).
    let callers = gq.find_callers("Context", 50, 0.0).unwrap();
    let caller_prod: Vec<_> = callers.iter().filter(|c| !c.is_test).collect();
    assert!(
        caller_prod.len() >= default_impact.direct_callers.len(),
        "callers must report at least as many prod users as impact direct: \
         callers={} impact_direct={}",
        caller_prod.len(),
        default_impact.direct_callers.len(),
    );
}
